//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogKodlama
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbBlogEntities : DbContext
    {
        public dbBlogEntities()
            : base("name=dbBlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_hakkimda> tbl_hakkimda { get; set; }
        public virtual DbSet<tbl_kategori> tbl_kategori { get; set; }
        public virtual DbSet<tbl_Ozgecmis> tbl_Ozgecmis { get; set; }
        public virtual DbSet<tbl_Resim> tbl_Resim { get; set; }
        public virtual DbSet<tbl_Egitim> tbl_Egitim { get; set; }
        public virtual DbSet<tbl_Beceri> tbl_Beceri { get; set; }
        public virtual DbSet<tbl_Becerikategori> tbl_Becerikategori { get; set; }
        public virtual DbSet<tbl_Ilgiler> tbl_Ilgiler { get; set; }
        public virtual DbSet<tbl_Oduller> tbl_Oduller { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_Logintalep> tbl_Logintalep { get; set; }
        public virtual DbSet<tbl_DKod> tbl_DKod { get; set; }
    }
}
