//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogKodlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Egitim
    {
        public int id { get; set; }
        public string okul { get; set; }
        public string fakulte { get; set; }
        public string bolum { get; set; }
        public string mort { get; set; }
        public string bastarih { get; set; }
        public string bittarih { get; set; }
    }
}
