//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogKodlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DKod
    {
        public int id { get; set; }
        public int kisi_id { get; set; }
        public string d_kod { get; set; }
        public Nullable<System.DateTime> code_date { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
