//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogKodlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Logintalep
    {
        public int id { get; set; }
        public string istek_ip { get; set; }
        public Nullable<int> is_login { get; set; }
        public Nullable<System.DateTime> istekk_date { get; set; }
    }
}
